config/routes.rb
resources :sage_associations
match '/settings/show_tracker_custom_fields/:type' => 'settings#show_tracker_custom_fields', :via => [:get, :post]
match '/settings/show_list_options' => 'settings#show_list_options', :via => [:get, :post]
match '/settings/show_tracker_statuses' => 'settings#show_tracker_statuses', :via => [:get, :post]

match '/sync_client_field' => 'custom_fields#sync_client_field', :via => [:get, :post]
match '/get_clients' => 'custom_fields#get_clients', :via => [:get, :post]

app/models/facturaplus_client.rb
class FacturaplusClient < ActiveRecord::Base
	def self.get_clients(biller)
		biller_association = SageAssociation.find_by_source_id_and_data_type(biller, 'Biller')
		if biller_association.present?
			self.where(biller_id: biller_association.target_code).map(&:client_name).sort
		else
			if Setting.plugin_redmine_facturaplus['default_clients'].present?
				return Setting.plugin_redmine_facturaplus['default_clients'].split("\r\n")
			else
				return []
			end
		end
	end
end

app/models/facturaplus_mailer.rb
CF_FACTURACION = 152;
CF_FECHA_FACTURACION = 153;

class FacturaplusMailer < Mailer
	def facturaplus_sync_error(issue)
	    @issue = issue
	    mail to: Setting.plugin_redmine_facturaplus['emails'], subject: l(:'facturaplus.email_subject')
	end

	def bill_changes(date)
		@facturas = JournalDetail.joins(:journal).where("DATE(journals.created_on) = ? AND journal_details.property = 'cf' AND journal_details.prop_key = ?", date, CF_FACTURACION).group_by{|e| e.journal.journalized_id}.map{|e,v| {:issue => e, :old => v.first.old_value, :new => v.last.value}}
		@fechas = JournalDetail.joins(:journal).where("DATE(journals.created_on) = ? AND journal_details.property = 'cf' AND journal_details.prop_key = ?", Date.today, CF_FECHA_FACTURACION).group_by{|e| e.journal.journalized_id}.map{|e,v| {:issue => e, :old => v.first.old_value, :new => v.last.value}}

	    mail to: Setting.plugin_redmine_facturaplus['emails'], subject: l(:'facturaplus.daily_email_subject')
	end
end

app/models/facturaplus_relation.rb
class FacturaplusRelation < ActiveRecord::Base
	belongs_to :issue

	def remove_delivery_note
		self.delivery_note_id = nil
		self.save
	end
end

app/models/sage_association.rb
class SageAssociation < ActiveRecord::Base

	def self.get_project_serial_from_business_line(business_line)
		sage_project_association = self.find_by_source_id_and_data_type(business_line, 'SageProject')
		if sage_project_association.present?
			self.find_by_source_id_and_data_type(sage_project_association.id, 'Serial')
		else
			nil
		end
	end

end

app/controllers/sage_associations_controller.rb
class SageAssociationsController < ApplicationController
  layout 'admin'
  before_filter :require_admin
  before_filter :get_type, :only => [:new, :edit]
  before_filter :get_source, :only => [:new, :edit]
  before_action :get_sage_association, only: [:edit, :update, :destroy]

  # GET /sage_associations
  # GET /sage_associations.json
  def index
    @sage_associations = SageAssociation.all
  end

  # GET /sage_associations/1
  # GET /sage_associations/1.json
  def show
  end

  # GET /sage_associations/new
  def new
    @sage_association = SageAssociation.new
  end

  # GET /sage_associations/1/edit
  def edit
  end

  # POST /sage_associations
  # POST /sage_associations.json
  def create
    @sage_association = SageAssociation.new(sage_association_params)

    if @sage_association.save
      flash[:notice] = l(:"facturaplus.sage_associations.text_create_notice")
      if params[:continue]
        redirect_to action: 'new', :type => params[:sage_association][:data_type]
      else
        redirect_to sage_associations_path
      end
    else
      flash[:error] = @sage_association.errors.full_messages.join('<br>').html_safe
      redirect_to action: 'new', :type => params[:sage_association][:data_type]
    end
  end

  # PATCH/PUT /sage_associations/1
  # PATCH/PUT /sage_associations/1.json
  def update
    if @sage_association.update(sage_association_params)
      flash[:notice] = l(:"facturaplus.sage_associations.text_update_notice")
      redirect_to sage_associations_path
    else
      flash[:error] = @sage_association.errors.full_messages.join('<br>').html_safe
      redirect_to action: 'edit', :id => params[:sage_association][:id], :type => params[:sage_association][:data_type]
    end
  end

  # DELETE /sage_associations/1
  # DELETE /sage_associations/1.json
  def destroy
    @sage_association.destroy
    flash[:notice] = l(:"facturaplus.sage_associations.text_delete_notice_success")
    redirect_to sage_associations_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_sage_association
      @sage_association = SageAssociation.find(params[:id]) if params[:id].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sage_association_params
      params.require(:sage_association).permit(:source_id, :source_name, :target_code, :data_type, :status)
    end

    # Obtiene el tipo de elemento que se está modificando (articles o billers)
    def get_type
      @type = params[:type].present? ? params[:type] : nil
    end

    # Obtiene los datos del origen necesarios (para servicios y emisores)
    def get_source
      case @type
      when 'Article'
          get_source_services
      when 'Biller'
          get_source_billers
      when 'Currency'
          get_source_currencies
      when 'Section'
          get_source_business_units
      when 'SageProject'
          get_source_business_lines
      when 'Serial'
          get_source_sage_projects
      end
    end

    def get_source_services
      @source = ProjectCustomField.find(Setting.plugin_redmine_facturaplus['service_field']).enumerations
    end

    def get_source_billers
      @source = IssueCustomField.find(Setting.plugin_redmine_facturaplus['biller_field']).enumerations
    end

    def get_source_currencies
      @source = IssueCustomField.find(Setting.plugin_redmine_facturaplus['currency_field']).enumerations
    end

    def get_source_business_units
      @source = ProjectCustomField.find(Setting.plugin_redmine_facturaplus['business_unit_field']).enumerations
    end

    def get_source_business_lines
      @source = ProjectCustomField.find(Setting.plugin_redmine_facturaplus['business_line_field']).enumerations
    end

    def get_source_sage_projects
      @source = SageAssociation.select("id, source_name AS name").where("data_type = ?",'SageProject')
    end
end

app/views/hooks/facturaplus/_view_issues_form_details_bottom.html.erb
<% content_for :header_tags do %>
  <%= javascript_include_tag 'sync', :plugin => 'redmine_facturaplus' %>
<% end %>

<% if Setting.plugin_redmine_facturaplus['bill_tracker'].present? and Setting.plugin_redmine_facturaplus['client_field'].present? and @issue.tracker_id.to_s == Setting.plugin_redmine_facturaplus['bill_tracker'] and User.current.allowed_to?(:clients_sync, @project) %>
<script>
$(document).ready(function(){
	client_field = $("#issue_custom_field_values_<%=Setting.plugin_redmine_facturaplus['client_field']%>");
	biller_field = $("#issue_custom_field_values_<%=Setting.plugin_redmine_facturaplus['biller_field']%>");
	sync_link = " <a href='#' class='icon icon-reload' onclick=\'if (confirm(\"<%=l(:'facturaplus.text_confirm_sync_client_field')%>\")){ sync_client_field(biller_field, client_field); }\'></a>";
	$(client_field).prev().append(sync_link);

	$(biller_field).on('change', function(){
		change_biller(biller_field, client_field);
	});
	change_biller(biller_field, client_field);
});
</script>

<% end %>

app/views/sage_associations/_form.html.erb
<%= error_messages_for @sage_association %>

<fieldset class="box tabular">
  <p>
    <%= f.select :source_id, options_from_collection_for_select(@source, :id, :name, @sage_association.source_id) %>
    <%= f.hidden_field :source_name %>
  </p>
  <p>
    <%= f.text_field :target_code %>
    <%= f.hidden_field :data_type, :value => @type %>
  </p>
  <% if @type == 'Biller' %>
    <p>
      <%= f.radio_button :status, 1, :checked => true %>
      <%= f.label :status, 'Disponible para facturar', :value => 1 %>
    </p>      
    <p>
      <%= f.radio_button :status, 2 %>
      <%= f.label :status, 'Solo listado', :value => 2 %>
    </p>
  <% end %>
</fieldset>

<script>

$(document).ready(function(){
  $('#sage_association_source_name').val($('#sage_association_source_id option:selected').text());

  $(document).on('change', '#sage_association_source_id', function(source_id){
    $('#sage_association_source_name').val($('#sage_association_source_id option:selected').text());
  });
});
</script>

app/views/sage_associations/edit.html.erb
<%= title l(:"facturaplus.label_edit_sage_#{@type.underscore}_association") %>

<%= labelled_form_for @sage_association, :html => {:id => 'issue-form', :multipart => true} do |f| %>
  <%= error_messages_for 'sage_associations' %>
  <div class="box tabular">
    <div id="all_attributes">
        <%= render :partial => 'sage_associations/form', :locals => {:f => f} %>
    </div>

  </div>

  <%= submit_tag l(:button_update) %>
<% end %>

<%= link_to l(:button_back), sage_associations_path %>

app/views/sage_associations/index.html.erb
<h2><%=l(:"facturaplus.label_sage_associations_settings")%></h2>

<div class="splitcontentleft">
  <h2><%=l(:"facturaplus.label_articles")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_article_association"), new_sage_association_path(:type => 'Article'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:"facturaplus.label_service_field")%></th>
        <th><%=l(:"facturaplus.label_service_name_field")%></th>
        <th><%=l(:"facturaplus.label_article_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'Article').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_id %></td>
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'Article'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2><%=l(:"facturaplus.label_sections")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_section_association"), new_sage_association_path(:type => 'Section'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:field_identifier)%></th>
        <th><%=l(:"facturaplus.label_business_unit_field")%></th>
        <th><%=l(:"facturaplus.label_section_code_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'Section').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_id %></td>
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'Section'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2><%=l(:"facturaplus.label_sage_projects")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_project_association"), new_sage_association_path(:type => 'SageProject'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:field_identifier)%></th>
        <th><%=l(:"facturaplus.label_business_line_field")%></th>
        <th><%=l(:"facturaplus.label_sage_project_code_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'SageProject').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_id %></td>
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'SageProject'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="splitcontentright">
  <h2><%=l(:"facturaplus.label_billers")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_biller_association"), new_sage_association_path(:type => 'Biller'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:"facturaplus.label_biller_field")%></th>
        <th><%=l(:"facturaplus.label_biller_name_field")%></th>
        <th><%=l(:"facturaplus.label_biller_code_field")%></th>
        <th><%=l(:"facturaplus.label_biller_status_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'Biller').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_id %></td>
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= sage_association.status == 1 ? '✓' : '' %>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'Biller'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2><%=l(:"facturaplus.label_currencies")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_currency_association"), new_sage_association_path(:type => 'Currency'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:"facturaplus.label_currency_field")%></th>
        <th><%=l(:"facturaplus.label_currency_name_field")%></th>
        <th><%=l(:"facturaplus.label_currency_code_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'Currency').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_id %></td>
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'Currency'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2><%=l(:"facturaplus.label_serials")%></h2>
  <div class="contextual">
    <%= link_to l(:"facturaplus.label_new_sage_serial_association"), new_sage_association_path(:type => 'Serial'), :class => 'icon icon-add'  %>
  </div>

  <table class="list">
    <thead>
      <tr>
        <th><%=l(:"facturaplus.label_sage_project_field")%></th>
        <th><%=l(:"facturaplus.label_serial_field")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sage_associations.where(data_type: 'Serial').each do |sage_association| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td><%= sage_association.source_name %></td>
          <td><%= sage_association.target_code %></td>
          <td><%= link_to l(:button_edit), edit_sage_association_path(sage_association, :type => 'Serial'), :class => 'icon icon-edit' %></td>
          <td><%= delete_link sage_association_path(sage_association.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sage_associations/new.html.erb
<%= title l(:"facturaplus.label_new_sage_#{@type.underscore}_association") %>

<%= labelled_form_for @sage_association, :url => sage_associations_path do |f| %>
  <%= error_messages_for 'sage_associations' %>
  <div class="box tabular">
    <div id="all_attributes">
        <%= render :partial => 'sage_associations/form', :locals => {:f => f} %>
    </div>

  </div>

  <%= submit_tag l(:button_create) %>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
<% end %>
<%= link_to l(:button_back), sage_associations_path %>

app/views/settings/_get_list_options.html.erb
<%if params[:custom_field].present?%>
<%=('<option></option>'+options_for_select(CustomField.find(params[:custom_field]).possible_values)).html_safe%>
<%else%>
<%='<option></option>'.html_safe%>
<%end%>

app/views/settings/_get_tracker_custom_fields.html.erb
<%if params[:tracker].present?%>
<%=('<option></option>'+options_from_collection_for_select(Tracker.find(params[:tracker]).custom_fields.where(field_format: params[:type]), :id, :name)).html_safe%>
<%else%>
<%='<option></option>'.html_safe%>
<%end%>

app/views/settings/_get_tracker_statuses.html.erb
<%if params[:tracker].present?%>
<%=('<option></option>'+options_from_collection_for_select(Tracker.find(params[:tracker]).issue_statuses, :id, :name)).html_safe%>
<%else%>
<%='<option></option>'.html_safe%>
<%end%>